itle: "Rafael Kracker Lerner"
description: "Analista de Testes e QA / Analista de Suporte | Portfólio profissional"
url: "https://rafaellerner.github.io"
github_username: rafaellerner
linkedin_username: rafael-lerner-389900114
email: lernerrafael@gmail.com
